[package]
name = "aptx_translator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
translation_api = { path = "../crates/translation_api" }
clap = { version = "4.4.3", features = ["derive"] }
ctrlc = { version = "3.4.1" }
sysexits = { version = "0.7.2" }
